base_link: 'base_link'

# =====================================================
gripper: # ee group name
  end_effector_name: 'gripper' # ee group name

  #actuated joints in end effector
  joints : ['gripper_finger_one']

  #open position
  pregrasp_posture : [0.0]
  pregrasp_time_from_start : 4.0

  #close position
  grasp_posture : [0.04]
  grasp_time_from_start : 4.0

  #desired pose from end effector to grasp - [x,y,z]
  grasp_pose_to_eef : [0 , 0, 0]

  #desired pose from end effector to grasp - [r, p, y]
  grasp_pose_to_eef_rotation : [0, 0 , 0] # 1.5707 = PI/2

  end_effector_parent_link : 'hand_tool'
